# %% [markdown]
# # L5: Data Analyst Agent 🤓

# %% [markdown]
# <div style="background-color:#fff6ff; padding:13px; border-width:3px; border-color:#efe6ef; border-style:solid; border-radius:6px">
# <p> 💻 &nbsp; <b>Access <code>requirements.txt</code> , notebooks and other files:</b> 1) click on the <em>"File"</em> option on the top menu of the notebook and then 2) click on <em>"Open"</em>.
# 
# <p> ⬇ &nbsp; <b>Download Notebooks:</b> 1) click on the <em>"File"</em> option on the top menu of the notebook and then 2) click on <em>"Download as"</em> and select <em>"Notebook (.ipynb)"</em>.</p>
# 
# <p> 📒 &nbsp; For more help, please see the <em>"Appendix – Tips, Help, and Download"</em> Lesson.</p>
# 
# </div>

# %% [markdown]
# <p style="background-color:#f7fff8; padding:15px; border-width:3px; border-color:#e0f0e0; border-style:solid; border-radius:6px"> 🚨
# &nbsp; <b>Different Run Results:</b> The output generated by AI chat models can vary with each execution due to their dynamic, probabilistic nature. Don't be surprised if your results differ from those shown in the video.</p>

# %% [markdown]
# First start by filtering warnings and loading environment variables.

# %%
# Warning control
import warnings
warnings.filterwarnings('ignore')

# %%
from helper import load_env
load_env()

# %%
!pip install -r requirements.txt

# %% [markdown]
# Now, let's create the data analyst agent. You will create a sandbox, then open the `pokemon.csv` dataset and write it to the sandbox as `data.csv`.

# %%
from lib.utils import create_sandbox

sbx = create_sandbox()

with open("pokemon.csv", "r", encoding="utf-8") as f:
    content = f.read()

sbx.files.write("data.csv", content)

# %% [markdown]
# Now you can import your `coding_agent` and modify the system prompt to let it know that the user has uploaded a dataset called `data.csv` and it should create interesting plots.

# %%
from lib.coding_agent import coding_agent, log
from lib.tools_schemas import execute_code_schema
from lib.tools import execute_code
from openai import OpenAI

client = OpenAI()

system = """You are a senior python programmer. 
You must run the code using the `execute_code` tool.
The user has uploaded a data.csv.
You help the user understanding the data 
by creating interesting plots.
"""

tools = { "execute_code" : execute_code }

# %% [markdown]
# Now you can query the data as normal and the sandbox will execute code on the data to answer the queries.

# %%
messages = []

query = "What is the data about?"

messages, usage = log(coding_agent,
    messages=messages,
    query=query,
    client=client,
    system=system,
    tools_schemas=[execute_code_schema],
    tools=tools,
    max_steps=10,
    sbx=sbx,
)

# %%
query = "Can you aggregate the pokemons by type?"

messages, usage = log(coding_agent,
    messages=messages,
    query=query,
    client=client,
    system=system,
    tools_schemas=[execute_code_schema],
    tools=tools,
    max_steps=10,
    sbx=sbx,
)

# %% [markdown]
# ### Gradio UI
# 
# You can use this provided Gradio UI to have a nicer user experience when chatting with your code generation agent. It will also give interesting information about the context stack, including the number of tokens used in the result, by the assistant, the user, and tools.

# %%
from lib.ui import ui

ui(coding_agent,
    messages,
    client=client,
    system=system,
    tools_schemas=[execute_code_schema],
    tools=tools,
    max_steps=10,
    sbx=sbx,
).launch(share=True, height=800)

# %% [markdown]
# ## Your Turn
# 
# Now it's your turn to explore this unknown dataset. Ask questions and learn more about the information inside.

# %%
# sbx = create_sandbox()
# with open("unknown.csv", "r", encoding="utf-8") as f:
#     content = f.read()
# sbx.files.write("data.csv", content)

# messages = []

# ui(
#     coding_agent,
#     messages,
#     client=client,
#     system=system,
#     tools_schemas=[execute_code_schema],
#     tools=tools,
#     max_steps=10,
#     sbx=sbx,
# ).launch(share=True, height=800)

# %%



